default: &default
  adapter: postgis
  host: localhost
  encoding: unicode
  username: formaloo_admin
  password: testpass1 #<-- which you have defiend while installing postgresql
  pool: 5

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>